# Generated by Django 4.1.7 on 2023-06-06 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transaction", "0002_transactions_initiated_by_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="sender",
            new_name="student",
        ),
        migrations.RemoveField(
            model_name="transactions",
            name="recipient",
        ),
        migrations.AddField(
            model_name="transactions",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.SmallIntegerField(
                choices=[(1, "Sent"), (2, "Refunded"), (3, "Paid Online")]
            ),
        ),
    ]
