# Generated by Django 4.1.7 on 2023-05-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="business_id",
        ),
    ]
