# Generated by Django 4.1.7 on 2023-06-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="initiated_by_student",
            field=models.BooleanField(default=True),
        ),
    ]
