# Generated by Django 4.1.7 on 2023-03-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="transaction_pin",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
