# Generated by Django 4.1.7 on 2023-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_rename_sender_transactions_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_status",
            field=models.SmallIntegerField(
                choices=[(1, "Success"), (0, "Failed"), (2, "Pending")]
            ),
        ),
    ]
