# Generated by Django 4.1.7 on 2023-03-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="business_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="business_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wallet_id",
            field=models.IntegerField(default=4212701031, unique=True),
        ),
    ]
