# Generated by Django 4.1.7 on 2023-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wallet_id",
            field=models.IntegerField(default=7450753193, unique=True),
        ),
    ]
