# Generated by Django 4.1.7 on 2023-03-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet_id",
            field=models.IntegerField(default=2206012281, unique=True),
        ),
    ]
