# Generated by Django 4.1.7 on 2023-03-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_customuser_email_alter_customuser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="business_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wallet_id",
            field=models.IntegerField(default=4909962027, unique=True),
        ),
    ]
