# Generated by Django 4.1.7 on 2023-03-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_customuser_wallet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="business_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="wallet_id",
            field=models.IntegerField(default=4484792222, unique=True),
        ),
    ]
