# Generated by Django 4.1.7 on 2023-04-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_transactions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
