# Generated by Django 4.1.7 on 2023-03-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_customuser_business_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="wallet_id",
            field=models.IntegerField(unique=True),
        ),
    ]
