# Generated by Django 4.1.7 on 2023-04-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_transactions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
