# Generated by Django 4.1.7 on 2023-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_transactions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="amuont",
            new_name="amount",
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                default="2d1efe23e5330d4fddee",
                max_length=20,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
