# Generated by Django 4.1.7 on 2023-04-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_amuont_transactions_amount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transactions",
        ),
    ]
