# Generated by Django 4.1.7 on 2023-04-08 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "Success"), (2, "Failed")]),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="type",
            field=models.SmallIntegerField(choices=[(1, "Sent"), (2, "Refunded")]),
        ),
    ]
