# Generated by Django 4.1.7 on 2023-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_transactions_amount_alter_transactions_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="was_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "Success"), (0, "Failed")]),
        ),
    ]
