# Generated by Django 4.1.7 on 2023-04-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.SmallIntegerField(choices=[(1, "Sent"), (2, "Refunded")]),
                ),
                (
                    "status",
                    models.SmallIntegerField(choices=[(1, "Success"), (0, "Failed")]),
                ),
                ("was_refunded", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
