# Generated by Django 4.1.7 on 2023-05-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="business_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
