# Generated by Django 4.1.7 on 2023-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_business_name_alter_user_wallet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="transaction_pin",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
