# Generated by Django 4.1.7 on 2023-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_transaction_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(unique=True),
        ),
    ]
