# Generated by Django 4.1.7 on 2023-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
